# This is a basic workflow to help you get started with Actions

name: Continuous Integration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0
      # Runs a set of commands using the runners shell
      - name: Run linting
        run: |
          echo Running linter...
          yarn lint
      # Runs a set of commands using the runners shell
      - name: Run tests
        run: |
          echo Running tests...
          yarn test --watchAll=false
